version: '3'
services:
  shop_api:
    build:
      context: .
    ports:
      - "8008:8000"
    env_file:
      .env 
    volumes:
      - .:app 
    depends_on:
      - db
      - redis
    command: sh -c "python manage.py runserver makemigrations  && python manage.py runserver migrate && python manage.py runserver && python manage.py runserver  0.0.0.0:8000"
  
  db:
    image: "postgres:14"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgressql/data

  redis:
    image: redis:7
    volumes:
    - redise_data:/data     

  celery_worker:
    build:
     context: .

    env_file:
      .env 
    volumes:
      - .:app 
    depends_on:
      - redis
    command: celery - A shop_api worker --Loglevel=info


  celery_beat:
    build:
     context: .

    env_file:
      .env 
    volumes:
      - .:app 
    depends_on:
      - redis
    command: celery - A shop_api beat --Loglevel=info


  celery_flower:
    build:
     context: .

    env_file:
      .env 
    volumes:
      - .:app 
    depends_on:
      - redis
    command: celery - A shop_api flower --Loglevel=info
    ports:
      - "5555:5555"
    

volumes:
 db_data:
 redise_data: